---
- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
      
  tasks:
  - name: Install stuff
    apt: name={{item}}
    with_items:
      - htop
      - tmux
      - mc
      - ncdu