---
- name: Global configuration
  hosts: all
  become: true

  vars:
    users:
      - username: zap
        visual_studio_code_extensions:
          - ms-vscode.csharp
          - jchannon.csharpextensions
          - jmrog.vscode-nuget-package-manager

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/vscode.yml
    - include: tasks/vscode_extensions.yml
      