---
- name: Global configuration
  hosts: all
  become: true

  vars:
    users:
      - username: zap
        visual_studio_code_extensions:
          # Microsoft
          - ms-vscode.csharp # C# for Visual Studio Code
          - jchannon.csharpextensions # C# Extensions
          - jmrog.vscode-nuget-package-manager # NuGet Package Manager
          # Angular
          - johnpapa.angular2 # Angular v6 Snippets
          - alexiv.vscode-angular2-files # Angular Files
          - Angular.ng-template # Angular Language Service
          # Generic
          - CoenraadS.bracket-pair-colorizer # Bracket Pair Colorizer
          - PKief.material-icon-theme # Material Icon Theme
          - christian-kohler.path-intellisense # Path Intellisense
          - esbenp.prettier-vscode # Prettier - Code formatter
          # Typescript
          - eg2.tslint # TSLint
          - rbbit.typescript-hero # TypeScript Hero
          # Debug
          - msjsdiag.debugger-for-chrome # Debugger for Chrome
        
      - username: zap
        atom_packages:
          - atom-hugo # Run the hugo commands from Atom
          - date # Insert the current date & time
          - language-hugo # Syntax higlight for Hugo files

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/vscode.yml
    - include: tasks/vscode_extensions.yml
  
  roles:
    - role: postman
    - role: atom